/** Teaching views only. All quantitative paths are drawn by the retained data renderer. */
export function laterScenes({trace,plotLabel,bracket}) {
  const packet=(id,whole=false)=>`<div class="packet-visual"><div class="event-overview">${plotLabel('The same packet, kept in view','3.4–5.4 s')}${trace(`${id}-overview`,'Filtered sigma overview; highlighted event from 3.875 to 4.875 seconds')}<div class="zoom-connector" aria-hidden="true"></div></div><div class="packet-focus">${plotLabel('Inside the spindle-like packet','a.u.')}${bracket(whole?'1.0 s / this event':'≈77 ms / cycle',whole?16.07:42.14,whole?71.43:5.495,'teal')}${trace(`${id}-focus`,'Enlarged filtered sigma packet from the same simulated record')}<div class="plot-context">${whole?'Illustrative event detection':'13 Hz simulated carrier'}<span>3.65–5.05 s</span></div></div></div>`;
  const power=(id,seconds)=>`<div class="power-visual" data-power-view="${id}">${id==='power'?`<div class="input-step">${plotLabel('Simulated EEG-like input','a.u.')}${trace('power-input','Unfiltered simulated EEG-like signal, before selecting the sigma band')}<span>↓ Select 10–16 Hz</span></div>`:''}<div class="context-track">${plotLabel('Filtered sigma signal · 10–16 Hz','a.u.')}${trace(`${id}-signal`,'Filtered sigma context track from the fixed simulated record')}</div><div class="analysis-operation"><span aria-hidden="true">↓</span><span>Square → average 0.5 s → low-pass</span></div><div class="derived-track">${plotLabel('Derived sigma power','a.u.²')}${trace(`${id}-power`,'Calculated sigma power from the same record and same time interval')}</div><div class="window-line"><span>Same simulated record</span><output data-window-for="${id}">${seconds} seconds in view</output></div></div>`;
  return [
    {id:'comparison',chapter:'Different patterns',title:'Similar speed. Different organization.',copy:'Alpha can appear during relaxed, eyes-closed wakefulness. Spindle-related sigma occurs in NREM sleep. These separate examples share a two-second view: a similar cycle speed does not make them the same pattern.',note:'Separate simulated examples · frequency bands overlap',source:'comparison',visual:()=>`<div class="comparison-visual"><div class="compare-reading blue">${plotLabel('Alpha <span class="context-state">· eyes-closed wake</span>','8–13 Hz')}${trace('comparison-alpha','Separate simulated waking alpha example, 3.4 to 5.4 seconds')}<span class="reading-unit">Continues across the window · a.u.</span></div><div class="compare-reading teal">${plotLabel('Sigma <span class="context-state">· NREM sleep</span>','10–16 Hz')}${trace('comparison-sigma','Separate simulated filtered sigma example, with a spindle-like packet marked at 3.875 to 4.875 seconds')}<span class="reading-unit">A brief packet swells and fades · a.u.</span></div><div class="shared-scale">Same 2-second time scale · amplitude scales differ</div></div>`},
    {id:'spindle',chapter:'Inside one event',title:'Fast cycles inside a brief event',copy:'Keep this packet’s place in the record as we enlarge it. Its simulated 13 Hz carrier repeats roughly every 77 milliseconds. Many electrical cycles fit inside the same spindle-like event.',note:'Simulated example · filtered 10–16 Hz signal',source:'spindle',visual:()=>packet('spindle')},
    {id:'event',chapter:'The whole event',title:'The event lasts longer than one cycle',copy:'Now measure the whole marked interval: 3.875 to 4.875 seconds. Our illustrative detector marks a one-second event. Its duration differs from the cycles inside it—and from the time until another event.',note:'Simulated example · illustrative detection, not a clinical classifier',source:'spindle',visual:()=>packet('event',true)},
    {id:'power',chapter:'A different measurement',title:'Track power in the chosen band',copy:'The upper trace still shows filtered signal values. Below it, a separate calculation measures power in that band. The time coordinates stay aligned, but the quantity and its units have changed.',note:'Simulated example · power is not an amplitude envelope or an event count',source:'power',visual:()=>power('power',2)},
    {id:'longer',chapter:'Look over a longer interval',title:'Let more of the record come into view',copy:'The observation window grows while the stored record stays fixed. Short bursts now sit within a longer stretch of time. The larger lower plot continues to show the same calculated power measurement.',note:'Simulated example · scrolling changes the view, not the biology',source:'iso',visual:()=>power('longer',8)},
    {id:'longer30',chapter:'Watch power vary',title:'Look beyond individual bursts',copy:'Across a wider interval, the amount of sigma power varies. The fast electrical signal remains as context above. Widening this view does not slow down its cycles or turn the signal into a new rhythm.',note:'Simulated example · fixed start at record time 3.4 s',source:'iso',visual:()=>power('longer30',30)},
    {id:'slow',chapter:'Slower organization',title:'Fast activity can have slower organization',copy:'Here the power changes over a much longer interval. This example was deliberately built with 60- and 90-second amplitude modulation. It demonstrates a construction; it does not establish a biological clock or identify every bump as an infraslow rhythm.',note:'Simulated example · built-in modulation, not an empirical discovery',source:'iso',hold:2,visual:()=>power('slow',120)},
    {id:'scales',chapter:'Keep the quantities distinct',title:'Three different meanings of time',copy:'A cycle repeats within a brief event. Modulation describes slower variation of a measurement across time. Comparing their durations helps us read the record; it does not make these quantities equivalent or prove they share a cause.',note:'Comparison of this simulated example · not universal physiological periods',source:'atlas',hold:1.3,visual:()=>`<div class="scale-summary"><div class="scale-example" data-scale="0"><h3>Electrical cycle</h3>${trace('scale-cycle','About one simulated 13 Hz carrier cycle')}<p>≈77 <span>milliseconds</span></p><span>One repetition inside the packet</span></div><div class="scale-example" data-scale="1"><h3>Event duration</h3>${trace('scale-event','The marked one-second simulated spindle-like event')}<p>1.0 <span>second</span></p><span>The whole marked interval</span></div><div class="scale-example" data-scale="2"><h3>Built-in modulation</h3>${trace('scale-modulation','Calculated power across the 120-second simulated interval')}<p>60 & 90 <span>seconds</span></p><span>Amplitude variation built into the example</span></div></div>`}
  ];
}
