import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {heroMarkup,mountHero,clamp,smooth} from './pulse-hero.js';
import {buildRecord} from './signal.js';
import {drawTrace,drawSpectrum,svgMarkup} from './plot.js';
import {sources} from './content.js';
import {introEvidence,introCopy} from './intro-evidence.js';
import {laterScenes} from './journey-scenes.js';
import {mountComparison,amplitudeMethod} from './teaching-views.js';
import {mountContinuity,motion} from './continuity.js';
import {methodMarkup} from './teaching-methods.js';
gsap.registerPlugin(ScrollTrigger);
const data=buildRecord();
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const trace=svgMarkup;
const plotLabel=(name,unit='a.u.')=>`<div class="plot-label"><span>${name}</span><span>${unit}</span></div>`;
const disclosure=scene=>{const text=scene.id==='recording'?'Literature-derived schematic · simulated trace':scene.note.replace(/^Separate simulated examples|^Simulated waking example|^Simulated example|^Comparison of this simulated example/,'Synthetic demonstration');return `<span class="scene-note scientific-disclosure">${text}</span>`;};
const bracket=(label,left,width)=>`<div class="measurement-overlay"><div class="measure-bracket" style="--measure-left:${left}%;--measure-width:${width}%"><span>${label}</span></div></div>`;
const windowControls=()=>`<div class="window-control" data-mode="guided"><div class="window-heading"><label for="window-slider">Observation window</label><output id="window-value" for="window-slider">2 seconds</output></div><input id="window-slider" type="range" min="0" max="1000" step="10" value="0" aria-valuetext="2 seconds, guided by scrolling" aria-describedby="window-help"><div class="window-presets" aria-label="Observation window presets">${[2,10,60,180].map(t=>`<button data-window="${t}">${t} s</button>`).join('')}<button id="resume-guided" hidden>Resume guided view ↗</button><span id="guided-label">Guided by scrolling</span></div><p id="window-help">Scroll to widen the view, or choose your own window.</p></div>`;
const recording=()=>`<div class="recording-visual"><svg class="scalp-diagram" viewBox="0 0 300 200" role="img" aria-label="Schematic scalp electrodes measure a voltage difference relative to a reference"><path d="M30 140 Q25 30 115 28 Q205 30 200 140"/><circle cx="53" cy="72" r="8"/><circle cx="181" cy="73" r="8"/><path d="M61 72H101V164H240M189 73H222V148H240"/><path d="M245 135V177M258 145V167"/><text x="26" y="188">Scalp electrodes</text><text x="228" y="118">ΔV</text></svg><div class="recording-signal">${plotLabel('EEG · voltage over time')}${trace('recording-trace','Separate simulated waking EEG example over one second')}<span class="plot-context">Simulated example · schematic measurement</span></div></div>`;
const scenes=[
 {id:'recording',chapter:'A different kind of record',title:'Observe from the scalp',copy:introCopy.S2,note:'A new measurement · separate from the illustrative motion',source:'intro',visual:recording},
 {id:'alpha',chapter:'A repeating cycle',title:'One cycle. Then another.',copy:'This simulated alpha example uses a 10 Hz carrier: about ten cycles each second. Posterior alpha is prominent during relaxed, eyes-closed wakefulness. Real EEG contains more than one pattern.',note:'Simulated waking example · alpha convention: 8–13 Hz',source:'alpha',visual:()=>`<div class="main-chart alpha-chart">${plotLabel('Alpha · eyes-closed wake')}${bracket('≈100 ms / cycle',20,10)}${trace('alpha-main','Simulated alpha, 4 to 5 seconds, with one approximate 100 millisecond cycle marked')}<div class="plot-context">1 second in view <span>Separate waking example</span></div></div>`},
 ...laterScenes({trace,plotLabel,bracket}).filter(s=>s.id!=='longer30')
];
const longer=scenes.find(s=>s.id==='longer');longer.visual=((original)=>()=>original()+windowControls())(longer.visual);longer.copy='The observation window grows while the stored record stays fixed. Short bursts sit within a longer stretch of time. The larger lower plot shows the same calculated power measurement.';
const presentation={
 alpha:{title:'A cycle is a repetition.',copy:'Ten cycles fit into this one-second, 10 Hz example. Posterior alpha is prominent in relaxed, eyes-closed wakefulness. Real EEG contains more than one pattern.'},
 comparison:{title:'Similar speed. Different state.',copy:'Two seconds of each example. Alpha belongs to relaxed, eyes-closed wakefulness; spindle-related sigma appears in NREM sleep. Similar cycle speeds can have different organization.'},
 spindle:{title:'One packet. Many cycles.'},
 event:{title:'A cycle is not an event.'},
 power:{title:'Change the measurement.',copy:'Keep the time interval. Square the filtered signal and average over 0.5 seconds, then low-pass and resample. The lower trace is power, in a.u.²—not voltage or an event count.'},
 longer:{title:'Change the window.'},
 slow:{title:'Fast activity. Slower organization.',copy:'The same power measurement, now across 180 seconds. This construction contains 60- and 90-second amplitude modulation; it demonstrates slower organization, not a discovered biological clock.'}
};
scenes.forEach(s=>Object.assign(s,presentation[s.id]||{}));
export function mountPulse(app){
 const previousRestoration=history.scrollRestoration;const keepHistoryManual=()=>{history.scrollRestoration='manual';};ScrollTrigger.addEventListener('refresh',keepHistoryManual);keepHistoryManual();
 const reduced=matchMedia('(prefers-reduced-motion:reduce)');
 const state={active:0,position:0,paused:false,linear:false,sourceOpen:false,manual:false,window:2,guidedProgress:0};
 let heroTrigger,scienceTrigger,windowTrigger,headerTrigger,observer,timer,step=700,travel=0,sceneOffsets=[],sceneSpans=[],focusBefore,restoring=false,destroyed=false,initialFrame;
 const evidence={...sources,intro:{...introEvidence,caveat:'Schematic electrode positions, not an activity map. The trace is simulated; it does not come from the illustration or a single neuron.'},power:{...sources.spindle,title:'A separate power measurement',summary:'For this demonstration, the filtered signal is squared and averaged over 0.5 seconds. Subsequent low-pass filtering and resampling retain a power time course. This is a calculated measurement of the same simulated record.'}};
 app.innerHTML=`<a class="skip-link" href="#recording">Skip to the scientific example</a><header class="site-header"><a class="brand" href="#opening" aria-label="Invisible Rhythms — return to opening"><span class="brand-mark" aria-hidden="true"></span><span class="brand-label">Invisible Rhythms</span></a><nav aria-label="Reading controls"><button id="context-evidence" data-source="intro" hidden>Evidence ↗</button><button id="motion-toggle" aria-pressed="false"><span class="motion-icon" aria-hidden="true">Ⅱ</span><span>Pause motion</span></button><button id="chapters-toggle" aria-expanded="false" aria-controls="chapters-menu">Chapters ⌄</button></nav><div id="chapters-menu" hidden><a href="#opening">The page has a pulse</a>${scenes.map(s=>`<a href="#${s.id}">${s.chapter}</a>`).join('')}</div></header><main>${heroMarkup()}<div class="science-run"><div class="science-stage">${scenes.map((s,i)=>`<article class="lesson" data-lesson="${s.id}" aria-labelledby="title-${s.id}"><figure class="scene-visual">${s.visual()}</figure><div class="scene-caption"><h2 id="title-${s.id}" tabindex="-1">${s.title}</h2><p class="lesson-copy">${s.copy}</p><div class="caption-foot">${disclosure(s)}</div></div></article>`).join('')}<div class="science-footer" aria-hidden="true"><span class="current-chapter"></span><span class="rhythm-progress"><i></i></span></div></div>${scenes.map((s,i)=>`<div class="scene-anchor" id="${s.id}" data-index="${i}" aria-hidden="true"></div>`).join('')}</div><footer class="journey-end"><h2>One record. Different questions.</h2><p>The measurement and its observation window shape what you can see.</p><a href="#opening">Return to the beginning ↑</a><button data-source="atlas">Explore the time reference ↗</button></footer></main><dialog id="evidence-dialog" aria-labelledby="evidence-title"><div class="dialog-toolbar"><span>Evidence & methods</span><button class="dialog-close">Close ×</button></div><div id="evidence-content"></div></dialog>`;
 const hero=mountHero(app),run=app.querySelector('.science-run'),stage=app.querySelector('.science-stage'),lessons=[...app.querySelectorAll('.lesson')],longerIndex=scenes.indexOf(longer),slider=app.querySelector('#window-slider'),dialog=app.querySelector('dialog');
 const comparisonView=mountComparison(lessons[2]);
 const continuity=mountContinuity(stage,lessons,data);
 const markedEvent=data.events.find(e=>Math.abs(e.start-3.875)<.01),cache=new Map();
 const guidedWindow=()=>{const p=clamp(state.guidedProgress)*3,i=Math.min(2,Math.floor(p)),values=[2,10,60,180];return Math.exp(Math.log(values[i])+(Math.log(values[i+1])-Math.log(values[i]))*smooth(p-i));};
 function plot(id,series,start,duration,opts={}){const svg=app.querySelector('#'+id);if(!svg)return;drawTrace(svg,series,{start,duration,range:series.displayRange,ticks:4,...opts});const axes=[...svg.querySelectorAll('.axis-label')];axes.forEach((el,i)=>{el.textContent=`${(start+duration*i/(axes.length-1)).toFixed(duration<2?2:1)}${i===axes.length-1?' s':''}`;});}
 function drawPower(id,duration,force=false){duration=Math.round(duration*10)/10;if(!state.linear&&!force){continuity.render(state.position,state.window);return;}if(!force&&cache.get(id)===duration)return;cache.set(id,duration);plot(id+'-signal',data.sigma,3.4,duration,{color:'var(--sigma)'});plot(id+'-power',data.power,3.4,duration,{color:'var(--power)',fill:true});app.querySelector(`[data-window-for="${id}"]`).textContent=`${duration} seconds in view`;}
 function updateWindow(force=false){if(!state.manual)state.window=guidedWindow();state.window=Math.round(state.window*10)/10;drawPower('longer',state.window,force);continuity.render(state.position,state.window);const viewKey=state.window+':'+state.manual;if(!force&&cache.get('window-ui')===viewKey)return;cache.set('window-ui',viewKey);slider.value=Math.round(Math.log(state.window/2)/Math.log(90)*1000);slider.setAttribute('aria-valuetext',`${state.window} seconds, ${state.manual?'manual view':'guided by scrolling'}`);app.querySelector('#window-value').textContent=`${state.window} seconds`;app.querySelector('.window-control').dataset.mode=state.manual?'manual':'guided';app.querySelector('#resume-guided').hidden=!state.manual;app.querySelector('#guided-label').hidden=state.manual;app.querySelectorAll('[data-window]').forEach(b=>b.setAttribute('aria-pressed',String(Math.abs(Number(b.dataset.window)-state.window)<.05)));app.querySelector('#window-help').textContent=state.manual?'Your window stays fixed here. Resume guided view to follow the scroll.':'Scroll to widen the view, or choose your own window.';lessons[longerIndex].querySelector('.lesson-copy').textContent=state.manual?`You are viewing ${state.window} seconds of the same stored record. The upper trace is filtered sigma; below it is calculated power. A short window resolves individual bursts. A longer view lets you compare how power varies.`:longer.copy;}
 function drawScene(id,force=false){
  if(id==='recording')plot('recording-trace',data.alpha,4,1,{color:'var(--recording)'});
  if(id==='alpha')plot('alpha-main',data.alpha,4,1,{color:'var(--recording)'});
  if(id==='comparison'){plot('comparison-alpha',data.alpha,3.4,2,{color:'var(--recording)'});plot('comparison-sigma',data.sigma,3.4,2,{color:'var(--sigma)',events:[markedEvent]});}
  if(id==='spindle'||id==='event'){plot(id+'-overview',data.sigma,3.4,2,{color:'var(--sigma)',events:[markedEvent]});plot(id+'-focus',data.sigma,3.65,1.4,{color:'var(--sigma)',events:id==='event'?[markedEvent]:[]});}
  if(id==='power')plot('power-input',data.raw,3.4,2,{color:'var(--ir-paper)'});
  if(id==='power'||id==='slow')drawPower(id,id==='power'?2:180,force);
  if(id==='longer')updateWindow(force);
  if(id==='scales'){plot('scale-cycle',data.sigma,4.24,1/13,{color:'var(--sigma)',showAxes:false});plot('scale-event',data.sigma,3.875,1,{color:'var(--sigma)',showAxes:false});plot('scale-modulation',data.power,3.4,120,{color:'var(--power)',fill:true,showAxes:false});}
 }
 function setActive(index){index=clamp(index,0,scenes.length-1);if(!restoring&&state.active===longerIndex&&index!==longerIndex&&state.manual){state.manual=false;updateWindow();}state.active=index;stage.dataset.scene=scenes[index].id;const access=app.querySelector('#context-evidence');access.dataset.source=scenes[index].source;access.setAttribute('aria-label',`Sources and methods: ${scenes[index].title}`);lessons.forEach((el,i)=>{const visible=state.linear||i===index;el.classList.toggle('is-active',visible);el.inert=!visible;el.setAttribute('aria-hidden',String(!visible));});app.querySelector('.current-chapter').textContent=scenes[index].chapter;drawScene(scenes[index].id);}
 function render(position){
  if(state.sourceOpen)return;state.position=clamp(position,0,scenes.length-.001);stage.style.setProperty('--journey-progress',state.position/scenes.length);const index=Math.floor(state.position),fraction=state.position-index;if(index!==state.active)setActive(index);
  if(index===longerIndex){state.guidedProgress=clamp(fraction/.76);updateWindow();}
  if(!state.linear){
   comparisonView(index===2?fraction:index<2?0:1,false);
   const blend=smooth((fraction-motion.handoffStart)/motion.handoffSpan);
   lessons.forEach((el,i)=>{const active=i===index,next=i===index+1&&blend>0;el.style.visibility=active||next?'visible':'hidden';el.style.opacity=active||next?'1':'0';el.classList.toggle('is-transitioning',blend>0&&(active||next));const figure=el.querySelector('.scene-visual'),caption=el.querySelector('.scene-caption');figure.style.opacity=active?1-blend:next?blend:0;figure.style.transform=`translateY(${active?-12*blend:next?12*(1-blend):0}px)`;caption.style.opacity=active?smooth(fraction/motion.captionIn)*(1-smooth((fraction-.60)/.14)):0;});
   lessons[longerIndex].querySelector('.window-control').style.opacity=index===longerIndex?1-smooth((fraction-.60)/.14):1;
   continuity.render(state.position,state.window);
  }
 }
 function redraw(){cache.clear();scenes.forEach(s=>drawScene(s.id,true));}
 function setup(){
  heroTrigger?.kill();scienceTrigger?.kill();windowTrigger?.kill();headerTrigger?.kill();observer?.disconnect();
  const heroLinear=reduced.matches||state.paused||innerHeight<680||innerWidth<360;state.linear=heroLinear||innerWidth<800||innerHeight<820;
  document.body.classList.toggle('hero-linear',heroLinear);document.body.classList.toggle('science-linear',state.linear);hero.setLinear(heroLinear);
  if(!heroLinear)heroTrigger=ScrollTrigger.create({trigger:hero.run,start:'top 64px',end:()=>`+=${innerHeight*1.5}`,onUpdate:self=>hero.seek(self.progress)});
  step=Math.max(600,innerHeight*.84);const weights=[.65,.85,1.35,.95,.7,1.25,1.8,1.45,.8];sceneSpans=weights.map(w=>w*step);let offset=0;sceneOffsets=sceneSpans.map(n=>{const start=offset;offset+=n;return start;});travel=offset;run.style.height=state.linear?'auto':`${travel+innerHeight-64}px`;
  app.querySelectorAll('.scene-anchor').forEach((el,i)=>{el.style.top=`${sceneOffsets[i]}px`;el.dataset.span=sceneSpans[i];});lessons.forEach((el,i)=>{el.id=state.linear?scenes[i].id+'-reading':'';});
  lessons.forEach(el=>{el.style.visibility='';el.style.opacity='';el.querySelector('.scene-visual').style.cssText='';el.querySelector('.scene-caption').style.opacity='';el.querySelector('.window-control')?.style.removeProperty('opacity');});setActive(state.active);redraw();continuity.measure(state.linear);comparisonView(state.position-2,state.linear);
  if(!state.linear)scienceTrigger=ScrollTrigger.create({trigger:run,start:'top 64px',end:()=>`+=${travel}`,onUpdate:self=>{const y=self.progress*travel,i=Math.max(0,sceneOffsets.findLastIndex(x=>x<=y));render(i+(y-sceneOffsets[i])/sceneSpans[i]);}});
  else{
   windowTrigger=ScrollTrigger.create({trigger:lessons[longerIndex],start:'top 75%',end:'top 15%',onUpdate:self=>{state.guidedProgress=self.progress;if(!state.sourceOpen&&!restoring)updateWindow();}});
   observer=new IntersectionObserver(()=>{if(state.sourceOpen||restoring)return;let index=state.active,amount=0;lessons.forEach((el,i)=>{const r=el.getBoundingClientRect(),n=Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,64));if(n>amount){amount=n;index=i;}});if(amount&&index!==state.active)setActive(index);const r=lessons[longerIndex].getBoundingClientRect();if(state.manual&&(r.bottom<=96||r.top>=innerHeight)){state.manual=false;updateWindow();}},{threshold:[0,.1,.25,.5,.75,1]});lessons.forEach(el=>observer.observe(el));
  }
  app.querySelector('#motion-toggle span:last-child').textContent=reduced.matches?'Reduced motion':state.paused?'Resume motion':'Pause motion';app.querySelector('#motion-toggle').disabled=reduced.matches;app.querySelector('#motion-toggle').setAttribute('aria-pressed',String(state.paused||reduced.matches));
  headerTrigger=ScrollTrigger.create({trigger:run,start:'top 100px',end:'bottom 64px',onToggle:self=>{app.querySelector('.site-header').classList.toggle('is-reading',self.isActive);app.querySelector('#context-evidence').hidden=!self.isActive;}});
  ScrollTrigger.refresh();
 }
 function targetY(id){if(id==='opening')return 0;const index=scenes.findIndex(s=>s.id===id);if(index<0)return null;return state.linear?lessons[index].getBoundingClientRect().top+scrollY-80:run.getBoundingClientRect().top+scrollY-64+sceneOffsets[index]+sceneSpans[index]*.55;}
 function goTo(id,push=true,focus=false){const y=targetY(id);if(y===null)return;if(push)history.pushState(null,'','#'+id);scrollTo({top:y,behavior:'instant'});ScrollTrigger.update();if(focus){const el=app.querySelector('#title-'+id);el?.focus({preventScroll:true});}closeChapters();}
 function stableSetup(){const inScience=run.getBoundingClientRect().top<innerHeight*.5,id=scenes[state.active].id,oldHero=hero.progress,wasLinear=state.linear,oldY=scrollY,oldFraction=state.position-state.active;restoring=true;setup();if(inScience){const y=targetY(id);scrollTo({top:!state.linear&&!wasLinear?y+(oldFraction-.55)*sceneSpans[state.active]:y,behavior:'instant'});}else if(!document.body.classList.contains('hero-linear'))scrollTo({top:oldHero*innerHeight*1.5,behavior:'instant'});else scrollTo({top:Math.min(oldY,hero.stage.clientHeight*.5),behavior:'instant'});ScrollTrigger.update();restoring=false;updateWindow(true);}
 slider.addEventListener('input',()=>{state.manual=true;state.window=2*Math.pow(90,Number(slider.value)/1000);updateWindow();});
 app.querySelectorAll('[data-window]').forEach(b=>b.addEventListener('click',()=>{state.manual=true;state.window=Number(b.dataset.window);updateWindow();}));
 app.querySelector('#resume-guided').addEventListener('click',()=>{state.manual=false;updateWindow();slider.focus({preventScroll:true});});
 app.querySelector('#motion-toggle').addEventListener('click',()=>{state.paused=!state.paused;stableSetup();});
 const menu=app.querySelector('#chapters-menu'),menuButton=app.querySelector('#chapters-toggle');function closeChapters(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');}
 menuButton.addEventListener('click',()=>{menu.hidden=!menu.hidden;menuButton.setAttribute('aria-expanded',String(!menu.hidden));});
 app.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();goTo(a.hash.slice(1),true,true);}));
 function showEvidence(key){const info=evidence[key];focusBefore=document.activeElement;state.sourceOpen=true;hero.stopIdle();app.querySelector('#evidence-content').innerHTML=`<h2 id="evidence-title">${escape(info.title)}</h2><p class="evidence-summary">${escape(info.summary)}</p><p class="evidence-caveat">${escape(info.caveat)}</p>${methodMarkup(key,data)}${amplitudeMethod(key,trace)}${info.papers.map(p=>`<article class="paper"><h3>${escape(p.title)}</h3><p>${escape(p.citationLabel||p.year)} · ${escape(p.population)}<br>${escape(p.depth)}</p><a href="${escape(p.url)}" target="_blank" rel="noopener noreferrer">Read the published source ↗</a></article>`).join('')}<p class="source-context">Published sources open in a separate tab. Your observation window stays here.</p>`;app.querySelectorAll('#evidence-content details').forEach(el=>el.addEventListener('toggle',()=>{const svg=el.querySelector('#method-spectrum');if(el.open&&svg){drawSpectrum(svg,data.spectrum);svg.dataset.unit='a.u.⁴/Hz';}if(el.open&&el.querySelector('#method-rms'))plot('method-rms',data.rms,3.4,2,{color:'var(--ir-blue)',events:[markedEvent]});}));document.body.style.overflow='hidden';dialog.showModal();dialog.querySelector('button').focus();}
 app.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',()=>showEvidence(b.dataset.source)));
 dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button:not([disabled]),a[href],summary')].filter(el=>el.getClientRects().length);if((e.shiftKey&&document.activeElement===controls[0])||(!e.shiftKey&&document.activeElement===controls.at(-1))){e.preventDefault();(e.shiftKey?controls.at(-1):controls[0]).focus();}});
 dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{state.sourceOpen=false;document.body.style.overflow='';focusBefore?.focus({preventScroll:true});});
 const keydown=e=>{if(e.key==='Escape'&&!menu.hidden){closeChapters();menuButton.focus();}};app.addEventListener('keydown',keydown);
 const onResize=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!destroyed)stableSetup();},180);},onPop=()=>goTo(location.hash.slice(1)||'opening',false),onVisibility=()=>{if(document.hidden)hero.stopIdle();},onReduced=()=>stableSetup();
 addEventListener('resize',onResize);addEventListener('popstate',onPop);document.addEventListener('visibilitychange',onVisibility);reduced.addEventListener('change',onReduced);
 setup();hero.welcome();initialFrame=requestAnimationFrame(()=>{redraw();if(location.hash)onPop();});
 return()=>{destroyed=true;ScrollTrigger.removeEventListener('refresh',keepHistoryManual);history.scrollRestoration=previousRestoration;clearTimeout(timer);cancelAnimationFrame(initialFrame);hero.destroy();continuity.destroy();heroTrigger?.kill();scienceTrigger?.kill();windowTrigger?.kill();headerTrigger?.kill();observer?.disconnect();removeEventListener('resize',onResize);removeEventListener('popstate',onPop);document.removeEventListener('visibilitychange',onVisibility);reduced.removeEventListener('change',onReduced);app.removeEventListener('keydown',keydown);document.body.style.overflow='';};
}
