export const scenes = [
  {id:'eeg',word:'EEG signals',eyebrow:'01 / EEG',title:'Scalp EEG measures voltage differences.',description:'Electrodes on the scalp record changing voltage differences. EEG reflects the combined activity of many cells—not the activity of a single neuron.',note:'EEG-like signal · arbitrary units',metric:'256',unit:'samples / second in this simulation',theme:'mineral',evidence:'eeg'},
  {id:'alpha',word:'Alpha oscillations',eyebrow:'02 / Alpha',title:'Frequency measures cycles per second.',description:'This alpha example has a nominal 10 Hz carrier—about ten cycles each second. Posterior alpha is prominent during relaxed, eyes-closed wakefulness. One 10 Hz cycle takes about 100 milliseconds.',note:'Independent alpha example · 10 Hz carrier',metric:'100',unit:'milliseconds / cycle',theme:'mineral',evidence:'alpha'},
  {id:'sigma',word:'Alpha and sigma',eyebrow:'03 / Comparison',title:'Alpha and sigma differ in physiological context.',description:'Alpha in wakefulness and spindle-related sigma in NREM sleep have overlapping frequency bands. These independent examples show different organisation; one does not turn into the other.',note:'Independent simulated examples · amplitude scales differ',metric:'10–16',unit:'Hz / sigma band used here',theme:'mineral',evidence:'sigma'},
  {id:'spindle',word:'Sleep spindles',eyebrow:'04 / Spindles',title:'A spindle event contains multiple cycles.',description:'Follow the marked interval into a closer view. About 77 milliseconds describes one carrier cycle. The selected spindle-like event contains many cycles and lasts one second.',note:'Same selected interval · 3.875–4.875 s',metric:'1.0',unit:'second / selected event',theme:'night',evidence:'spindle'},
  {id:'power',word:'Sigma power',eyebrow:'05 / Power',title:'Power is derived from the filtered sigma signal.',description:'Square the filtered sigma signal and average locally, then smooth it. The lower trace is calculated power. It shares the time axis with the signal, but has squared units.',note:'Sigma → square → 0.5 s mean → low-pass',metric:'a.u.²',unit:'power, not an event count',theme:'night',evidence:'power'},
  {id:'window',word:'Observation window',eyebrow:'06 / Window',title:'Expand the time window of the same record.',description:'Widen the view of the same record. Its samples, event times and power calculation stay fixed. Scroll to expand, or take control below.',note:'Same data · start 3.65 s · fixed y scales',metric:'180',unit:'seconds / longest displayed window',theme:'violet',evidence:'window'},
  {id:'slow',word:'Infraslow modulation',eyebrow:'07 / Infraslow',title:'Simulated modulation produces slower power variation.',description:'The simulation includes 60- and 90-second amplitude variation. Its calculated power shows slower organisation. This demonstrates a measurement—not the discovery of a biological clock.',note:'Simulated amplitude modulation · not slow EEG voltage',metric:'< 0.1',unit:'Hz / infraslow timescale',theme:'violet',evidence:'slow'}
];
