import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {buildRecord} from './signal.js';
import {sources,atlas,processS} from './content.js';
import {drawTrace,drawSpectrum,svgMarkup} from './plot.js';
import {windowMarkup,mountWindow} from './openings.js';

gsap.registerPlugin(ScrollTrigger);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sourceButton=(key,label='Sources & method')=>`<button class="source-button" data-source="${key}">${label} <span aria-hidden="true">↗</span></button>`;
const logPosition=s=>(Math.log10(s)+2)/7;
const atlasLink={alpha:'#alpha',sigma:'#spindles',iso:'#discovery'};
const clockFormat=s=>s<1?`${Math.round(s*1000)} ms`:s<60?`${Number(s.toFixed(1))} s`:s<3600?`${Number((s/60).toFixed(1))} min`:`${Number((s/3600).toFixed(1))} h`;

export function mountSlice(app){
  const data=buildRecord(),media=matchMedia('(prefers-reduced-motion: reduce)');
  const state={manualPause:false,reduced:media.matches,sourceOpen:false,hidden:document.hidden,alphaPlaying:false,alphaTime:4,observation:1,atlasScale:1,step:0,isoWindow:120,spindleView:'cycles'};
  const isPaused=()=>state.manualPause||state.reduced||state.sourceOpen||state.hidden;
  const brand=`<a class="brand" href="#opening" aria-label="Invisible Rhythms home"><span class="brand-mark" aria-hidden="true">i:r</span><span>Invisible<br>Rhythms</span></a>`;
  app.innerHTML=`
  <a class="skip-link" href="#atlas">Skip opening and explore time</a>
  <header class="header site-header">${brand}<span class="header-note">An inquiry into biological time</span><nav aria-label="Main navigation"><a href="#atlas">Time atlas <span aria-hidden="true">↗</span></a><a href="?study=window" class="studies-link">Opening studies</a><button class="motion-button" aria-pressed="${isPaused()}"><span class="motion-dot" aria-hidden="true"></span><span>${isPaused()?'Motion paused':'Pause motion'}</span></button></nav></header>
  <main>
  <section id="opening" class="hero section-dark" aria-labelledby="opening-title">
    <div class="hero-intro"><div><p class="eyebrow"><span class="small-rule"></span>Invisible Rhythms / First encounter</p><h1 id="opening-title">You are<br><span>never still.</span></h1></div><div class="hero-note"><p>A beat. A breath.<br>Changes too slow to notice.</p><p class="micro">An interactive scientific exhibition.<br>No live measurements. Just a longer look.</p></div></div>
    ${windowMarkup('opening')}
    <div class="hero-exit"><p class="micro">You changed the view.<br>The record stayed the same.</p><a class="continue-link" href="#atlas"><span>Take your window<br>into the time atlas</span><span class="round-arrow" aria-hidden="true">↓</span></a></div>
  </section>

  <section id="atlas" class="atlas-section paper-section" aria-labelledby="atlas-title">
    <div class="section-mast"><p class="eyebrow">01 / The time atlas</p>${sourceButton('atlas')}</div>
    <div class="section-intro"><h2 id="atlas-title">Time is only<br>half the story.</h2><div class="intro-copy"><p>Compare how long things take.<br>Their position tells you nothing about what causes what.</p><p class="micro">Literature-derived schematic · selected comparison anchors</p></div></div>
    <div class="atlas-window"><span class="eyebrow">Your window on a wider map</span><output class="atlas-output" for="atlas-range">1 s</output><label for="atlas-range" class="sr-only">Time atlas comparison scale</label><input id="atlas-range" type="range" min="0" max="1000" value="286" aria-valuetext="1 second comparison scale"/><span class="micro">Drag the same boundary to compare a different scale.</span></div>
    <div class="atlas-map"><div class="atlas-axis"><span>Observable</span><div class="axis-ticks">${['10 ms','1 s','1 min','1 h','1 day'].map((label,i)=>`<span style="left:${[0,28.571,53.974,79.377,99.1][i]}%">${label}</span>`).join('')}</div><span>Time quantity</span></div><div class="atlas-rows">${atlas.map((entry,i)=>`<div class="atlas-row ${entry.available?'available':'unbuilt'}" data-atlas-seconds="${entry.seconds}"><div class="atlas-name"><span class="mono">${String(i+1).padStart(2,'0')}</span>${entry.available?`<a href="${atlasLink[entry.id]}">${entry.name}<span aria-hidden="true">↗</span></a>`:`<span>${entry.name}</span>`}</div><div class="atlas-track"><span class="atlas-coordinate" style="left:${logPosition(entry.seconds)*100}%"><i></i><b>${entry.timeLabel}</b></span></div><div class="atlas-kind"><span>${entry.quantity}</span><span class="micro">${entry.available?'In this prototype':'Not built in this slice'}</span></div></div>`).join('')}</div><div class="atlas-compare-line" aria-hidden="true"></div></div>
    <div class="atlas-foot"><p class="micro">Equal distance means a ratio of duration, not equal biological meaning.<br>50 s locates a study-dependent ISO window; 96 min is one study median; 24 h is a daily display anchor.</p><details><summary>${processS.label} <span aria-hidden="true">+</span></summary><p>${processS.summary} No fixed period is assigned.</p></details></div>
    <a class="chapter-link" href="#alpha">Begin with an electrical rhythm <span aria-hidden="true">↓</span></a>
  </section>

  <section id="alpha" class="alpha-section section-dark" aria-labelledby="alpha-title"><div class="section-mast"><p class="eyebrow">02 / A familiar speed</p>${sourceButton('alpha')}</div>
    <div class="alpha-layout"><div class="alpha-type"><span class="alpha-symbol" aria-hidden="true">α</span><h2 id="alpha-title">Alpha.</h2><p class="large-caption">Too fast to feel.<br>Slow enough to examine.</p></div><div class="alpha-reading"><div class="stat-line"><p class="big-stat">8–13<span>Hz</span></p><p class="micro">Electrical cycles per second<br>Posterior alpha · eyes-closed wake</p></div><p>Frequency describes speed. To understand a rhythm, we also need to know where it is measured—and in which state.</p><div class="alpha-plot">${svgMarkup('alpha-trace','Synthetic alpha example with 10 Hz carrier, 4 to 5 seconds',230)}</div><div class="alpha-controls"><button class="text-button" id="alpha-play">Trace one second <span aria-hidden="true">→</span></button><span class="micro" id="alpha-clock">Paused · data time 4.00 s</span><button class="text-button" id="alpha-step">Step 0.1 s</button></div><p class="micro">Synthetic demonstration · 10 Hz carrier · a.u.<br>Playhead at 0.1× data time. The trace itself does not flash.</p></div></div>
    <div class="section-bottom"><p class="eyebrow">A frequency band is a convention.<br>It is not a complete identity.</p><a href="#comparison" class="continue-link">What happens at a similar speed? <span aria-hidden="true">↓</span></a></div>
  </section>

  <section id="comparison" class="comparison-section section-dark" aria-labelledby="comparison-title"><div class="section-mast"><p class="eyebrow">A necessary distinction</p>${sourceButton('comparison')}</div><h2 id="comparison-title" class="comparison-title">Similar speed.<br><span>Different state.</span></h2><div class="comparison-grid"><article><div class="comparison-label"><h3>Alpha</h3><p class="eyebrow">Quiet wakefulness</p></div>${svgMarkup('compare-alpha','Separate synthetic alpha record at the same two-second scale as the spindle example',170)}<p>A posterior rhythm, often waxing and waning during eyes-closed wake.</p><p class="micro">Project band: 8–13 Hz · synthetic example · a.u.</p></article><article><div class="comparison-label"><h3>Sigma</h3><p class="eyebrow">NREM sleep</p></div>${svgMarkup('compare-sigma','Filtered synthetic sigma record, showing transient packet structure over two seconds',170)}<p>Spindle-related spectral activity. A burst is an event within a chosen band.</p><p class="micro">Project band: 10–16 Hz · synthetic example · a.u.</p></article></div><div class="comparison-foot"><div class="band-key"><span>8</span><span class="alpha-band">Alpha</span><span class="sigma-band">Sigma</span><span>16 Hz</span></div><p>These are separate examples at the same time scale.<br>Alpha does not turn into sigma.</p></div><a href="#spindles" class="chapter-link">Look inside a burst <span aria-hidden="true">↓</span></a></section>

  <section id="spindles" class="spindle-section paper-section" aria-labelledby="spindle-title"><div class="section-mast"><p class="eyebrow">03 / Inside the event</p>${sourceButton('spindle')}</div><div class="section-intro"><h2 id="spindle-title">A band.<br>A burst.<br>Two ideas.</h2><div class="intro-copy"><p>Power measures how much activity is present in a chosen band.<br><br>A spindle marks a particular burst.</p><p class="micro">Synthetic demonstration · not a clinical spindle detector</p></div></div>
    <div class="spindle-observation"><div class="spindle-toolbar"><div role="group" aria-label="Spindle reading"><button class="reading-tab" data-spindle="cycles" aria-pressed="true">Electrical cycles</button><button class="reading-tab" data-spindle="power" aria-pressed="false">Power</button><button class="reading-tab" data-spindle="events" aria-pressed="false">Event detection</button></div><span class="mono">Same interval / 3.4–5.4 s</span></div><div class="spindle-plot">${svgMarkup('spindle-trace','Synthetic filtered spindle example within a two-second observation window',230)}</div><div class="spindle-measure"><div><p class="eyebrow" id="spindle-measure-label">Inside the burst</p><p class="measure-number" id="spindle-measure-number">≈77<span>ms / cycle</span></p></div><div class="spindle-reading-copy"><p id="spindle-explanation">A 13 Hz carrier repeats about every 77 milliseconds. The packet lasts much longer than any one electrical cycle.</p><p class="micro" id="spindle-unit">Filtered 10–16 Hz · voltage-like amplitude in a.u.</p></div></div></div><a class="chapter-link" href="#discovery">Now change what you observe <span aria-hidden="true">↓</span></a></section>

  <section id="discovery" class="discovery-section section-dark" aria-labelledby="discovery-title"><div class="section-mast"><p class="eyebrow">04 / Rhythms within rhythms</p>${sourceButton('iso')}</div><div class="section-intro"><h2 id="discovery-title">The fast signal<br>has a slower story.</h2><div class="intro-copy"><p>First change the measurement.<br>Then watch it for longer.</p><p class="micro">Analysis is not biological transformation.<br>This example deliberately contains slow modulation.</p></div></div>
    <div class="discovery-grid"><div class="analysis-narrative">${[
      ['Start with the record.','A synthetic electrical record combines a fast packeted carrier with slower and faster background components.','EEG-like signal · 256 samples/s'],
      ['Choose a band.','An actual 10–16 Hz filter selects the activity we will examine. The original record remains visible.','Operation / band-pass filter'],
      ['Calculate power.','Square the filtered values and average them over 0.5 seconds. The new row measures power, not voltage or event count.','Operation / smoothed mean square'],
      ['Look for longer.','A wider window reveals the deliberately constructed variation. Its spectrum describes this demonstration; it does not validate a biological clock.','View / 25–100 s is a literature window, not a universal period']
    ].map((a,i)=>`<article class="analysis-beat" data-beat="${i}"><button class="beat-heading" data-step="${i}"><span class="mono">0${i+1}</span><h3>${a[0]}</h3></button><p>${a[1]}</p><p class="micro">${a[2]}</p></article>`).join('')}</div>
    <div class="science-dock"><div class="dock-top"><p class="eyebrow">The same record, read differently</p><span class="mono" id="analysis-counter">01 / 04</span></div><div class="analysis-controls" role="group" aria-label="Analysis controls">${['Record','Band','Power','Longer'].map((t,i)=>`<button data-step="${i}" aria-pressed="${i===0}"><span>0${i+1}</span> ${t}</button>`).join('')}<button class="analysis-source" data-source="iso">Sources <span aria-hidden="true">↗</span></button></div><p class="analysis-description" aria-live="polite"></p><div class="analysis-view"><div class="temporal-anchor" aria-hidden="true"></div>${[
      ['raw','EEG-like record','a.u.'],['sigma','Filtered 10–16 Hz','a.u.'],['power','Derived sigma power','a.u.²']
    ].map(([key,label,unit],i)=>`<div class="analysis-row row-${key}" data-row="${i}"><div class="row-label"><span>${label}</span><span>${unit}</span></div>${svgMarkup(`analysis-${key}`,`${label}, derived from the same deterministic synthetic record`,104)}</div>`).join('')}</div><div class="analysis-window-tools"><label for="iso-window">Observation window <output id="iso-duration">8 s</output></label><input id="iso-window" type="range" min="0" max="100" value="70" aria-valuetext="120 second observation window" disabled/><div class="window-presets"><button data-iso-window="30" disabled>30 s</button><button data-iso-window="120" disabled>120 s</button><button data-iso-window="236" disabled>236 s</button></div></div><p class="micro dock-interval" id="dock-interval">All rows: 4–12 s · same record interval</p><div class="spectrum-block" hidden><div class="spectrum-heading"><span class="eyebrow">Spectrum of calculated power</span><span class="micro">Full 240 s record</span></div>${svgMarkup('iso-spectrum','Calculated spectrum of synthetic sigma power; no statistical significance claim',170)}<p class="micro">Largest bin within 0.01–0.04 Hz: <span id="spectrum-peak"></span><br>Power PSD: a.u.⁴/Hz · mean removed, Hann window.</p></div><p class="simulation-note">Synthetic demonstration.<br>60 s and 90 s amplitude modulation were put into the record.</p><div class="dock-mobile-next"><button class="text-button" data-step-back>Previous</button><button class="text-button" data-step-next>Next reading →</button></div></div></div>
  </section>

  <section id="endpoint" class="endpoint paper-section"><p class="eyebrow">End of this prototype / the question remains open</p><h2>A longer look.<br><span>A different question.</span></h2><div class="endpoint-bottom"><p>Biological rhythms can be organized across time in several different ways.<br><br>What these patterns do—and why they move together—is a further question.</p><div><a href="#opening" class="solid-button">Look again <span aria-hidden="true">↗</span></a><a href="?study=layers" class="text-button">Compare the opening alternative ↗</a></div></div><footer><span>Invisible Rhythms / Local prototype</span><span>The broader journey is not built in this slice.</span><button class="source-button" data-source="iso">Evidence & limitations ↗</button></footer></section>
  </main><dialog id="sources-dialog" aria-labelledby="source-title"><div class="dialog-top"><span class="eyebrow">Investigate / reading state</span><button class="dialog-close" aria-label="Close sources">Close ×</button></div><div id="sources-content"></div></dialog>`;

  const cleanup=[];let frame=0,lastFrame=0,focusBefore=null,openingWindow;
  const navScroll=(target)=>document.querySelector(target)?.scrollIntoView({behavior:isPaused()?'instant':'smooth',block:'start'});
  document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const hash=a.getAttribute('href');if(document.querySelector(hash)){e.preventDefault();history.pushState(null,'',hash);navScroll(hash);}}));
  const onPop=()=>{if(location.hash)navScroll(location.hash);else scrollTo({top:0,behavior:'instant'});};addEventListener('popstate',onPop);cleanup.push(()=>removeEventListener('popstate',onPop));
  function renderMotion(){const b=document.querySelector('.motion-button');b.setAttribute('aria-pressed',String(isPaused()));b.querySelector('span:last-child').textContent=isPaused()?(state.reduced?'Reduced motion':'Motion paused'):'Pause motion';document.body.classList.toggle('motion-paused',isPaused());b.disabled=state.reduced;if(isPaused()){stopAlpha();gsap.getTweensOf('.analysis-row').forEach(t=>t.progress(1));}else{document.querySelector('#alpha-play').disabled=false;document.querySelector('#alpha-play').innerHTML='Trace one second <span aria-hidden="true">→</span>';}}
  document.querySelector('.motion-button').addEventListener('click',()=>{state.manualPause=!state.manualPause;renderMotion();setupScrollMotion();});
  const onReduced=e=>{state.reduced=e.matches;renderMotion();setupScrollMotion();setStep(state.step,{force:true});};media.addEventListener('change',onReduced);cleanup.push(()=>media.removeEventListener('change',onReduced));
  const onVisibility=()=>{state.hidden=document.hidden;renderMotion();};document.addEventListener('visibilitychange',onVisibility);cleanup.push(()=>document.removeEventListener('visibilitychange',onVisibility));

  function updateAtlas(value){state.atlasScale=value;const percent=logPosition(value)*100;document.querySelector('.atlas-output').textContent=clockFormat(value);document.querySelector('#atlas-range').value=Math.round(percent*10);document.querySelector('#atlas-range').setAttribute('aria-valuetext',`${clockFormat(value)} comparison scale`);document.querySelector('.atlas-map').style.setProperty('--compare-position',`${percent}%`);document.querySelectorAll('[data-atlas-seconds]').forEach(row=>row.classList.toggle('near-scale',Math.abs(Math.log10(Number(row.dataset.atlasSeconds)/value))<.42));}
  openingWindow=mountWindow(document.querySelector('.observation'),{onChange:d=>{state.observation=d;updateAtlas(d);},reduce:isPaused});cleanup.push(()=>openingWindow.destroy());
  document.querySelector('#atlas-range').addEventListener('input',e=>updateAtlas(10**(Number(e.target.value)/1000*7-2)));
  // Accessible numeric alternatives persist even when presentation motion is paused.
  function renderAlpha(){drawTrace(document.querySelector('#alpha-trace'),data.alpha,{start:4,duration:1,range:data.alpha.displayRange,cursor:state.alphaTime,color:'var(--accent)',ticks:4});document.querySelector('#alpha-clock').textContent=`${state.alphaPlaying?'Playing at 0.1×':'Paused'} · data time ${state.alphaTime.toFixed(2)} s`;}
  function stopAlpha(){state.alphaPlaying=false;cancelAnimationFrame(frame);lastFrame=0;const b=document.querySelector('#alpha-play');if(b){b.disabled=state.reduced||state.manualPause;b.innerHTML=b.disabled?'Playback paused · use Step':'Trace one second <span aria-hidden="true">→</span>';}if(document.querySelector('#alpha-trace'))renderAlpha();}
  function tick(now){if(!state.alphaPlaying||isPaused())return stopAlpha();if(lastFrame)state.alphaTime+=Math.min(now-lastFrame,100)/1000*.1;lastFrame=now;if(state.alphaTime>=5){state.alphaTime=5;stopAlpha();return;}renderAlpha();frame=requestAnimationFrame(tick);}
  document.querySelector('#alpha-play').addEventListener('click',()=>{if(state.alphaPlaying)return stopAlpha();if(isPaused())return;if(state.alphaTime>=5)state.alphaTime=4;state.alphaPlaying=true;document.querySelector('#alpha-play').textContent='Pause playhead Ⅱ';lastFrame=0;frame=requestAnimationFrame(tick);});
  document.querySelector('#alpha-step').addEventListener('click',()=>{stopAlpha();state.alphaTime=state.alphaTime>=4.99?4:Math.min(5,state.alphaTime+.1);renderAlpha();});
  const alphaVisibility=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stopAlpha();});alphaVisibility.observe(document.querySelector('#alpha'));cleanup.push(()=>alphaVisibility.disconnect());
  function renderSpindle(){const key=state.spindleView==='power'?'power':'sigma';document.querySelector('#spindle-trace').setAttribute('aria-label',({cycles:'Filtered synthetic sigma signal, amplitude in arbitrary units',power:'Calculated synthetic sigma power in squared arbitrary units',events:'Filtered synthetic sigma signal with illustrative detected event intervals'}[state.spindleView])+'; record time 3.4 to 5.4 seconds');drawTrace(document.querySelector('#spindle-trace'),data[key],{start:3.4,duration:2,range:data[key].displayRange,events:state.spindleView==='events'?data.events:[],ticks:4});const text={cycles:['Inside the burst','≈77<span>ms / cycle</span>','A 13 Hz carrier repeats about every 77 milliseconds. The packet lasts much longer than any one electrical cycle.','Filtered 10–16 Hz · voltage-like amplitude in a.u.'],power:['A derived measurement','0.5<span>s averaging window</span>','The filtered signal is squared and locally averaged, then smoothed and sampled at 8 Hz. Power and amplitude have different units.','Calculated power · a.u.² · not an amplitude envelope'],events:['One detected interval','1.0<span>s / demo event</span>','Here a simple RMS threshold marks 3.875–4.875 s. That event duration is different from the cycles inside it, or the time until another event.','Illustrative RMS detector · threshold 0.43 a.u., duration 0.5–2 s']}[state.spindleView];['spindle-measure-label','spindle-measure-number','spindle-explanation','spindle-unit'].forEach((id,i)=>document.getElementById(id).innerHTML=text[i]);document.querySelectorAll('[data-spindle]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.spindle===state.spindleView)));}
  document.querySelectorAll('[data-spindle]').forEach(b=>b.addEventListener('click',()=>{state.spindleView=b.dataset.spindle;renderSpindle();}));

  function drawAnalysis(){const duration=state.step===3?state.isoWindow:8;['raw','sigma','power'].forEach(key=>drawTrace(document.getElementById(`analysis-${key}`),data[key],{start:4,duration,range:data[key].displayRange,ticks:4,fill:key==='power',color:key==='power'?'var(--accent)':'currentColor'}));document.querySelector('#iso-duration').textContent=`${Math.round(duration)} s`;document.querySelector('#iso-window').value=Math.round((Math.log(state.isoWindow)-Math.log(25))/(Math.log(236)-Math.log(25))*100);document.querySelector('#iso-window').setAttribute('aria-valuetext',`${Math.round(duration)} second observation window`);document.querySelector('#dock-interval').textContent=`All rows: 4–${Math.round(4+duration)} s · ${duration>12?'voltage extrema retained per display column':'same record interval'}`;if(state.step===3)drawSpectrum(document.querySelector('#iso-spectrum'),data.spectrum);}
  function setStep(next,{force=false}={}){next=Math.max(0,Math.min(3,next));if(state.step===next&&!force)return;state.step=next;document.querySelector('.analysis-description').textContent=['Start with a synthetic electrical record. The time coordinate belongs to the fixed record.','Apply a 10–16 Hz band-pass filter. A new reading is calculated from the original record.','Calculate 0.5 s mean-square power, then low-pass and sample it at 8 Hz. Units change from a.u. to a.u.².','Widen the view. This example intentionally contains 60 s and 90 s modulation; its peak is not a biological discovery.'][next];document.querySelector('[data-step-back]').disabled=next===0;document.querySelector('[data-step-next]').disabled=next===3;document.querySelector('.science-dock').dataset.step=next;document.querySelector('#analysis-counter').textContent=`0${next+1} / 04`;document.querySelectorAll('.analysis-controls [data-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.step)===next)));document.querySelectorAll('.analysis-beat').forEach(b=>b.classList.toggle('active',Number(b.dataset.beat)===next));document.querySelector('#iso-window').disabled=next!==3;document.querySelectorAll('[data-iso-window]').forEach(b=>b.disabled=next!==3);document.querySelector('.spectrum-block').hidden=next!==3;const rows=document.querySelectorAll('.analysis-row');gsap.to(rows,{y:i=>next===0?80+i*6:next===1?i*118: i*100,opacity:i=>next===0?(i===0?1:0):next===1?(i<2?1:0):1,duration:isPaused()?0:.5,ease:'power2.inOut',overwrite:true});rows.forEach((r,i)=>r.setAttribute('aria-hidden',String(i>Math.min(next,2))));document.querySelector('.temporal-anchor').style.opacity=next===0?'0':'.35';drawAnalysis();}
  document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{setStep(Number(b.dataset.step));}));
  document.querySelector('[data-step-back]').addEventListener('click',()=>setStep(state.step-1));document.querySelector('[data-step-next]').addEventListener('click',()=>setStep(state.step+1));
  document.querySelector('#iso-window').addEventListener('input',e=>{state.isoWindow=Math.exp(Math.log(25)+Number(e.target.value)/100*(Math.log(236)-Math.log(25)));drawAnalysis();});
  document.querySelectorAll('[data-iso-window]').forEach(b=>b.addEventListener('click',()=>{state.isoWindow=Number(b.dataset.isoWindow);drawAnalysis();}));
  document.querySelector('#spectrum-peak').textContent=`${data.spectrum.peak.frequency.toFixed(4)} Hz (${data.spectrum.peak.period.toFixed(0)} s)`;

  let triggers=[],decorations=[];
  function setupScrollMotion(){triggers.forEach(t=>t.kill());decorations.forEach(t=>t.kill());triggers=[];decorations=[];if(!state.reduced&&!state.manualPause){document.querySelectorAll('.section-intro h2,.comparison-title,.endpoint h2').forEach(h=>decorations.push(gsap.fromTo(h,{y:22},{y:0,ease:'none',scrollTrigger:{trigger:h,start:'top 95%',end:'top 55%',scrub:true}})));}else gsap.set('.section-intro h2,.comparison-title,.endpoint h2',{clearProps:'transform'});if(innerWidth>900){document.querySelectorAll('.analysis-beat').forEach((beat,i)=>triggers.push(ScrollTrigger.create({trigger:beat,start:'top 54%',end:'bottom 54%',onEnter:()=>{if(!state.sourceOpen)setStep(i);},onEnterBack:()=>{if(!state.sourceOpen)setStep(i);}})));}ScrollTrigger.refresh();}
  const modal=document.querySelector('#sources-dialog');
  modal.addEventListener('keydown',e=>{
    if(e.key!=='Tab')return;
    const focusable=[...modal.querySelectorAll('button:not([disabled]),a[href],summary,input:not([disabled]),[tabindex="0"]')].filter(el=>el.getClientRects().length);
    const first=focusable[0],last=focusable.at(-1);
    if(!first)return;
    if((e.shiftKey&&document.activeElement===first)||(!e.shiftKey&&document.activeElement===last)||!modal.contains(document.activeElement)){
      e.preventDefault();(e.shiftKey?last:first).focus();
    }
  });
  function showSources(key){const info=sources[key];focusBefore=document.activeElement;state.sourceOpen=true;stopAlpha();renderMotion();gsap.getTweensOf('.analysis-row').forEach(t=>t.progress(1));document.querySelector('#sources-content').innerHTML=`<h2 id="source-title">${escape(info.title)}</h2><p class="source-summary">${escape(info.summary)}</p><p class="source-caveat">${escape(info.caveat)}</p>${['spindle','iso'].includes(key)?`<details class="method-details"><summary>How this demonstration is calculated +</summary><p>240 s of deterministic synthetic data, sampled at 256 Hz. A centered 257-tap FIR filter selects 10–16 Hz. Power is a 0.5 s moving mean square, low-pass filtered at 2 Hz before 8 Hz sampling. RMS is its square root; it is not power.</p><p>A simple detector uses RMS ≥0.43 a.u. for 0.5–2 s. This is not a validated clinical detector. The first and last 2 s are boundary-sensitive. Rare negative smoothing undershoots are floored to zero (${data.metadata.clippedNegativeSamples} values in this fixed record).</p><p>The power spectrum uses all 240 s, mean removal and a Hann window (resolution 0.00417 Hz; plotted here to 0.06 Hz). Its ordinate is a.u.⁴/Hz. A 60 s and 90 s modulation was deliberately constructed. No biological validation, surrogate significance test or private data is involved.</p></details>`:''}<p class="eyebrow source-list-title">Selected published evidence</p>${info.papers.map(p=>`<article class="source-paper"><p class="micro">${p.id} / ${p.year}</p><h3><a href="${escape(p.url)}" target="_blank" rel="noopener noreferrer">${escape(p.title)} ↗</a></h3><p class="micro">${escape(p.population)}<br>${escape(p.depth)}</p></article>`).join('')}<details class="claim-details"><summary>Evidence identifiers +</summary><p class="mono">${info.claims.map(escape).join(' · ')}</p></details><p class="micro source-note">A selected subset of the approved research package. These original summaries retain the review depth and limitations of that package.</p>`;document.body.style.overflow='hidden';modal.showModal();modal.querySelector('.dialog-close').focus();}
  document.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',()=>showSources(b.dataset.source)));
  modal.querySelector('.dialog-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
  modal.addEventListener('close',()=>{state.sourceOpen=false;document.body.style.overflow='';renderMotion();focusBefore?.focus({preventScroll:true});});
  function redraw(){renderAlpha();renderSpindle();drawTrace(document.querySelector('#compare-alpha'),data.alpha,{start:3.4,duration:2,range:data.alpha.displayRange});drawTrace(document.querySelector('#compare-sigma'),data.sigma,{start:3.4,duration:2,range:data.sigma.displayRange});drawAnalysis();}
  let resizeTimer;const resize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{redraw();setupScrollMotion();setStep(state.step,{force:true});},150);};addEventListener('resize',resize);cleanup.push(()=>{removeEventListener('resize',resize);clearTimeout(resizeTimer);});
  redraw();setStep(0,{force:true});setupScrollMotion();renderMotion();if(location.hash)setTimeout(()=>navScroll(location.hash),80);
  return()=>{cleanup.forEach(fn=>fn());stopAlpha();triggers.forEach(t=>t.kill());decorations.forEach(t=>t.kill());gsap.killTweensOf('.analysis-row');};
}
